spring:
  application:
    name: discord-server
  
  
  # MySQL R2DBC Configuration  
  r2dbc:
    url: r2dbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  # MongoDB Configuration
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  security:
    cors-allowed-origins:
      - "http://localhost:3000"
    public-urls:
      - "/api/v1/auth/**"
      - "/actuator/health"
      - "/docs/**"
      - "/webjars/**"
      - "/v3/api-docs/**"
      - "/api/test/**"

springdoc:
  swagger-ui:
    enabled: false

kakao:
  auth:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI}